# Numpy Starting 

In [2]:
#import numpy library
import numpy as np


In [3]:
#create numpy array  
## 1st is to convert a list to a numpy array
lst=[1,2,3,4,5]
np.array(lst)

array([1, 2, 3, 4, 5])

In [4]:
##nasted list to Nd arry
lst=[[1,2],[3,4],[5,6]]
np.array(lst) 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
## array creation using arange function 
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
## create one dimention zero array
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
## create 2 * 3 dimentional zeros array 
np.zeros((1,5))
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
## create linear space data form we need that lin space function
np.linspace(1,10,2)

array([ 1., 10.])

In [9]:
## random distribution of data
### uniform distribution
np.random.rand(1)
np.random.rand(5)
# generate a 2D arrary 
np.random.rand(3,4)

array([[0.27934744, 0.17421902, 0.61598795, 0.81651705],
       [0.1544628 , 0.36838803, 0.02963125, 0.09679232],
       [0.46466466, 0.55594653, 0.77391066, 0.92441948]])

In [10]:
## standard distribution
np.random.randn(2,3)

array([[-0.96067237, -0.07115542,  1.75131175],
       [-0.27643886, -0.4130021 ,  1.22452129]])

In [11]:
## random integer generation 
np.random.randint(low=1,high=100,size=(3,4))
## set boundary for the genration lower bound 
np.random.randint([1,2,3], 4)# make sure that the lower bound is less than  the upper bound
## set upper boundary 
np.random.randint(1,[3,4,6])
## set the lower and uppre bound 
np.random.randint([1,2],[2,4])      

array([1, 3], dtype=int32)

In [12]:
##set 2d boundation 
np.random.randint([1,2],[[3],[4]])

array([[2, 2],
       [1, 3]], dtype=int32)

In [13]:
## creation of n*m array with random intiger values
np.random.randint(1,101,(2,2))

array([[79, 99],
       [26, 49]], dtype=int32)

In [17]:
## Reshape the size of the array 
array=np.arange(0,10,1)
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [ ]:
#Indexing and Slicing and selection of the element 
