In [1]:
import numpy as np

In [2]:
#create an array 
arr= np.arange(1,11)

In [3]:
# select the single value from 1 d array 
arr[0] # pass the index value 

np.int64(1)

In [4]:
# slicing of the array 
arr[0:3] #[start:end:step_size]

array([1, 2, 3])

In [5]:
# broadcasting
arr[0:3]=10

In [6]:
arr

array([10, 10, 10,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#Note: when we are doing the broadcasting the shape of the array should be compatible and in this case its effect the original array 

In [8]:
# 2d array creation 
arr2d=np.random.randint(1,2,(2,5))

In [9]:
# grab data from 2d array 
arr2d=np.arange(9).reshape(3,3)
arr2d


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr2d[0][0] # access the element at first row and first column
arr2d[0,0] # access the element at first row and first column
arr2d[0]

array([0, 1, 2])

In [11]:
# slicing of 2d array 
arr2d[0:][1:][0][1:]
arr2d[1:,1:][1:][0][0]

np.int64(7)

In [12]:
## conditional selection
arr=np.arange(1,11)
boolean_array=arr>4
arr[boolean_array]
## in one liner 
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
#TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
len(dice_rolls[dice_rolls>2])
dice_rolls[dice_rolls>2]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [14]:
import numpy as np 
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_rolls_over_two = dice_rolls[dice_rolls>2] 
np.prod(total_rolls_over_two.shape)

np.int64(19)