In [1]:
import numpy as np

In [2]:
arr=np.arange(0,10)

In [3]:
## scaler addition
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
## array addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# 2d matrix design 
arr2d=np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
## sum on accross row
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [10]:
## sum accross column 
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [11]:
# total sum 
arr2d.sum()

np.int64(300)

In [12]:
## division by 0
arr / 0

C:\Users\ANIBRATA\AppData\Local\Temp\ipykernel_13772\1421493190.py:2: RuntimeWarning: divide by zero encountered in divide
  arr / 0
C:\Users\ANIBRATA\AppData\Local\Temp\ipykernel_13772\1421493190.py:2: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])